# Generated by Django 4.2.6 on 2024-01-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_type', models.CharField(choices=[('1', 'Permanent'), ('2', 'Contractual Non-Teaching'), ('3', 'Contractual Teaching'), ('4', 'Security')], max_length=40)),
                ('sequence_no', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(choices=[('1', 'Mr.'), ('2', 'Mrs.'), ('3', 'Dr.')], max_length=1)),
                ('first_name', models.CharField(default='', max_length=30)),
                ('middle_name', models.CharField(default='', max_length=30)),
                ('last_name', models.CharField(default='', max_length=30)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('aadhar_id', models.CharField(default='', max_length=20)),
                ('pan_no', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(default='', max_length=30)),
                ('mobile_no', models.CharField(default='', max_length=20)),
                ('address', models.CharField(default='', max_length=100)),
                ('date_of_joining', models.DateField()),
                ('date_of_relieving', models.DateField()),
                ('date_of_increment', models.DateField()),
                ('date_of_retirement', models.DateField()),
                ('from_appointment_date', models.DateField()),
                ('to_appointment_date', models.DateField()),
                ('designation_nature', models.CharField(choices=[('1', 'Permanent'), ('2', 'Permanent Teaching Non-Sanctioned'), ('3', 'Permanent Non-Teaching Excess'), ('4', 'Contractual Non-Teaching'), ('5', 'Contractual Teaching')], max_length=20)),
                ('department', models.CharField(choices=[('1', 'ACCOUNTS'), ('2', 'ADMIN'), ('3', 'CHEMISTRY'), ('4', 'CIVIL'), ('5', 'COMPUTER'), ('6', 'ELECTRONICS COMPUTER'), ('7', 'ELECTRICAL'), ('8', 'ESTABLISHMENT'), ('9', 'EXAM'), ('10', 'HOSTEL'), ('11', 'HUMANITIES'), ('12', 'LIBRARY'), ('13', 'MAINTENANCE'), ('14', 'MATHS'), ('15', 'MCA'), ('16', 'MECHANICAL'), ('17', 'PHYSICS'), ('18', 'PRODUCTION'), ('19', 'STRUCTURAL'), ('20', 'TEXTILE'), ('21', 'GYMKHANA'), ('22', 'STORE'), ('23', 'W/M SECURITY'), ('24', 'TPO')], max_length=20)),
                ('designation', models.CharField(choices=[('1', 'Professor'), ('2', 'Training and Placement Officer'), ('3', 'Junior Engineer'), ('4', 'System Manager'), ('5', 'CA'), ('6', 'Instructor'), ('7', 'Junior Clerk'), ('8', 'Junior Lab Assistant'), ('9', 'Lab Assistant'), ('10', 'Lab Attendant'), ('11', 'Lecturer'), ('12', 'Lib Attendant'), ('13', 'Library Clerk'), ('14', 'Mali'), ('15', 'Med Officer'), ('16', 'M Supervisor'), ('17', 'OSD'), ('18', 'Others'), ('19', 'Peon'), ('20', 'Senior Clerk'), ('21', 'Head Clerk'), ('22', 'Foreman'), ('23', 'Carpenter'), ('24', 'Adjunct faculty'), ('25', 'Adhoc faculty'), ('26', 'Tenure faculty'), ('27', 'Driver'), ('28', 'Assistant Professor'), ('29', 'Director'), ('30', 'STENO (M)'), ('31', 'D O'), ('32', 'Superintendent'), ('33', 'Assistant Instructor'), ('34', 'Accounts Officer'), ('35', 'System Engineer'), ('36', 'Office Assistant'), ('37', 'Watch Man'), ('38', 'Watch Man'), ('39', 'Hamal'), ('40', 'Sweeper'), ('41', 'Electrician'), ('42', 'Plumber'), ('43', 'System Analyst')], max_length=20)),
                ('appointment', models.CharField(choices=[('0', 'Please Select'), ('1', 'Regular'), ('2', 'DCPS'), ('3', 'Contractual NO EPF'), ('4', 'Contractual'), ('5', 'Contractual NT')], max_length=1)),
                ('staff_type', models.CharField(choices=[('1', 'CLASS 1'), ('2', 'CLASS 2'), ('3', 'CLASS 3'), ('4', 'CLASS 4'), ('5', 'OTHER'), ('6', 'CONTRACTUAL'), ('7', 'CONTRACTUAL NT')], max_length=1)),
                ('TA', models.BooleanField()),
                ('HRA', models.BooleanField()),
                ('handicap', models.BooleanField()),
                ('quarter', models.BooleanField()),
                ('senior_citizen', models.BooleanField()),
                ('quarter_type', models.CharField(choices=[('1', 'CLASS 1'), ('2', 'CLASS 2'), ('3', 'CLASS 3'), ('4', 'CLASS 4')], max_length=1)),
                ('bank_acc_no', models.CharField(max_length=20)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('bank_name', models.CharField(choices=[('0', 'Please Select'), ('1', 'State Bank of India'), ('2', 'Bank Of Maharashtra')], max_length=1)),
                ('bank_branch', models.CharField(max_length=30)),
                ('epf', models.CharField(max_length=20)),
                ('gpf_no', models.CharField(max_length=20, unique=True)),
                ('dcps_no', models.CharField(max_length=20, unique=True)),
                ('rule', models.CharField(choices=[('1', 'R7'), ('2', 'R6'), ('3', 'LUMSUM'), ('4', 'Daily Wages ')], max_length=1)),
                ('pay_level', models.CharField(choices=[('1', 'S-1(15000-47600)'), ('2', 'S-2(15300-48700)'), ('3', 'S-3(16600-52400)'), ('4', 'S-4(17100-54000)'), ('5', 'S-5(18000-56900)'), ('6', 'S-6(19900-63200)'), ('7', 'S-7(21700-69100)'), ('8', 'S-8(25500-81100)'), ('9', 'S-9(26400-83600)'), ('10', 'S-10(29200-92300)'), ('11', 'S-11(30100-95100)'), ('12', 'S-12(32000-101600)'), ('13', 'S-13(35400-112400)'), ('14', 'S-14(38600-122800)'), ('15', 'S-15(41800-132300)'), ('16', 'S-16(44900-142400)'), ('17', 'S-17(47600-151100)'), ('18', 'S-18(49100-155800)'), ('19', '1-1(0)'), ('20', '15600-39100(5000)'), ('21', '9A(56100-177500)'), ('22', '10(57700-182400)'), ('23', '11(68900-205500)'), ('24', '12(79800-211500)'), ('25', '13A1(131400-217100)'), ('26', '14(144200-218200)'), ('27', 'LUMSUM')], max_length=30)),
                ('cell_number', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15')], max_length=10)),
                ('basic', models.IntegerField(default=0)),
                ('pay_status', models.BooleanField()),
                ('grade_pay', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Salary', models.IntegerField()),
            ],
        ),
    ]
