# Generated by Django 4.2.6 on 2024-01-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_details',
            name='id_no',
            field=models.PositiveIntegerField(default=1, unique=True),
        ),
    ]
