# Generated by Django 4.2.6 on 2023-10-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('father_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=30)),
                ('jntu_no', models.CharField(max_length=30)),
                ('acite_id', models.CharField(max_length=30)),
                ('employee_no', models.IntegerField()),
                ('aadhar_or_unique_id', models.IntegerField()),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('cell_no', models.IntegerField()),
                ('Bloodgroup', models.CharField(max_length=10)),
                ('date_of_joining', models.DateField()),
                ('date_of_relieving', models.DateField()),
                ('date_of_increment', models.DateField()),
                ('pay_revised_date', models.DateField()),
                ('date_of_retirement', models.DateField()),
                ('from_appointment_date', models.DateField()),
                ('to_appointment_date', models.DateField()),
                ('designation_nature', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('appointment', models.CharField(max_length=30)),
                ('staff_type', models.CharField(max_length=30)),
                ('bank_name', models.CharField(max_length=30)),
                ('vocational', models.CharField(max_length=30)),
                ('bank_branch', models.CharField(max_length=30)),
                ('user_type', models.CharField(max_length=30)),
                ('appoint_in', models.CharField(max_length=30)),
                ('TA', models.BooleanField(default=True)),
                ('handicap', models.BooleanField(default=False)),
                ('quarter', models.BooleanField(default=False)),
                ('senior_citizen', models.BooleanField(default=False)),
                ('quarter_rent', models.BooleanField(default=False)),
                ('quarter_type', models.CharField(max_length=30)),
                ('bank_acc_no', models.IntegerField()),
                ('ifsc_code', models.IntegerField()),
                ('epf', models.IntegerField()),
                ('ppf_no', models.IntegerField()),
                ('pf_no', models.IntegerField()),
                ('pan_no', models.IntegerField()),
                ('rule', models.CharField(max_length=30)),
                ('scale', models.CharField(max_length=30)),
                ('pay_level', models.CharField(max_length=30)),
                ('cell_number', models.CharField(max_length=30)),
                ('basic', models.IntegerField()),
                ('pay_status', models.BooleanField(max_length=30)),
                ('grade_pay', models.CharField(max_length=30)),
                ('remark', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Salary', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
