# Generated by Django 4.2.6 on 2024-01-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_employee_details_id_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_details',
            name='id_no',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
