# Generated by Django 4.2.6 on 2023-10-30 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_employee_details_salary_user_login_delete_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_details',
            name='date_of_increment',
        ),
    ]
