# Generated by Django 4.2.6 on 2023-10-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_remove_employee_details_date_of_increment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_details',
            name='quarter_rent',
            field=models.BooleanField(default=True),
        ),
    ]
