# Generated by Django 4.2.6 on 2024-01-06 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_alter_employee_details_id_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_details',
            name='id_no',
        ),
    ]
