# Generated by Django 4.2.6 on 2023-10-30 08:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_alter_employee_details_quarter_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_details',
            name='date_of_increment',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
