# Generated by Django 4.2.6 on 2023-10-30 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_employee_details_date_of_increment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_details',
            name='date_of_increment',
        ),
    ]
