# Generated by Django 4.2.6 on 2023-10-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_remove_employee_details_date_of_increment'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_details',
            name='date_of_increment',
            field=models.DateField(null=True),
        ),
    ]
