# Generated by Django 4.2.6 on 2023-11-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_employee_details_date_of_increment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_details',
            old_name='appoint_in',
            new_name='appointed_in',
        ),
        migrations.AddField(
            model_name='employee_details',
            name='id_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee_details',
            name='sequence_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee_details',
            name='shift_joining',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee_details',
            name='shift_relieving',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='cell_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='employee_no',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='pan_no',
            field=models.CharField(max_length=10),
        ),
    ]
