# Generated by Django 4.2.6 on 2023-11-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_rename_appoint_in_employee_details_appointed_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_details',
            name='bank_acc_no',
            field=models.CharField(max_length=20),
        ),
    ]
