# Generated by Django 4.2.6 on 2023-11-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_delete_user_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_details',
            name='aadhar_or_unique_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='acite_id',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='epf',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='id_no',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='ifsc_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='jntu_no',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='pan_no',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='pf_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='ppf_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employee_details',
            name='sequence_no',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
